# Generated by Django 5.1.2 on 2024-10-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Commande'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit'},
        ),
    ]
