# Generated by Django 5.1.2 on 2024-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='nb_products',
            field=models.IntegerField(default=0),
        ),
    ]
